export const stories = [
  {
    profileImg: "./assets/profile-1.png",
    profileName: "219Labs",
    title: [
      "Explora nuestra landingpage",
      "y conoce todos nuestros",
      "servicios y planes.",
    ],
    linkLabel: "Descubrí",
    linkSrc: "https://219labs.vercel.app/",
    storyImg: "./assets/story-1.png",
  },
  {
    profileImg: "./assets/profile-2.png",
    profileName: "Instagram",
    title: ["Seguinos en Instagram", "y participá en sorteos", "regalamos contenido diario."],
    linkLabel: "Seguinos",
    linkSrc: "https://www.instagram.com/canepadev/",
    storyImg: "./assets/story-2.png",
  },
  {
    profileImg: "./assets/profile-3.png",
    profileName: "Whatsapp",
    title: ["Ponete en contacto", "directo por Whatsapp", "y conoce los servicios."],
    linkLabel: "Contacto",
    linkSrc: "https://api.whatsapp.com/send/?phone=5493816671884&text=Hola,%20quiero%20contratar%20tus%20Web%20Services.&type=phone_number&app_absent=0",
    storyImg: "./assets/story-3.png",
  },
  {
    profileImg: "./assets/profile-4.png",
    profileName: "Tik Tok",
    title: ["Aprende nuevos tips", "con nuestro contenido", "gratuito de Tiktok."],
    linkLabel: "Explorá",
    linkSrc: "https://www.tiktok.com",
    storyImg: "./assets/story-4.png",
  },
  {
    profileImg: "./assets/profile-5.png",
    profileName: "Youtube",
    title: ["Aprende a programar", "con nuestros tutoriales", "totalmente gratis. "],
    linkLabel: "Explore",
    linkSrc: "https://www.youtube.com/@CanepaDev",
    storyImg: "./assets/story-5.png",
  },
  {
    profileImg: "./assets/profile-6.png",
    profileName: "Linkedin",
    title: ["Ponete en contacto", "directo conmigo", "en Linkedin."],
    linkLabel: "Contacto",
    linkSrc: "https://www.linkedin.com/in/juan-c%C3%A1nepa-970559b9/",
    storyImg: "./assets/story-6.png",
  },
];
